os: linux
dist: xenial
language: node_js

node_js:
- lts/*

script:
- echo "Fix the tests at some point please!"

before_deploy: npm run build
deploy:
  provider: npm
  skip_cleanup: true
  tag: alpha  # TODO - remove when not alpha anymore
  on:
    tags: true
    repo: beer-garden/angular-schema-form-builder
  email: buildbot@beer-garden.io
  api_token:
    secure: p7123TfYZo8nrE0lBrWN5FAuzDCvflaNqFAWyihc1rx5SMfbTtSTHtMBNxW68d8NbXjwOGsZEJZpS7NpsTTcfRZMOr2UJu1IQWtSnqaySIUSGkUVSyzPh5lkdX04rRabg754cCLd45GjpN3WD8kg4mJll8EVnH+VPR+dB2wB7mlgi8Y6J2FnFGLIQAdKdAAZjD07Ozb8P2P6NZyLqFa2WoznE4FsVbNUuuVCMHffw81DstGP67y1C6X4mJIrbqK5Gu7eDeRkHdOknVwr8YTy3kNqixsy4+i3duo4amzG/C9cMHNb/vIhAME/MxAaGvrOmtMnNkzqfN9HgWlQ19CVzMiXceUZpO8zSdgM/UEzv4pGITYf3GdVQ79fxJ8CgXhBmXyL4xr20dYtVsr8NNFMD7leb6tHzkIgQFhavHoyYc5cqqHeu/s+rnTiiDoDn1OpP5IXVo1jgfhgoAgXsy4/3xc7X++IIl0NqztuLDaw6ydDujEZeKRrDoNn5M6zDdtg5XI01zPsrGrUNFz0zgLFxq/3WdH9cD2LAL4VbHIjwSXFiv7uWPoCSPzQV/zoqPlXR9lVocPaK7BK5Q4RxYYhao4Q7daiS2zF1jCXfcMU7cxodMf+74mBRDNGqzlyNdqoMHP9YON2GJHOIUXJQKAQh2YgAOni7WF6rDNUrfK+Skg=

