language: node_js
node_js:
  - lts/*

script:
  - echo "Fix the tests at some point please!"

before_deploy: npm run build

deploy:
  provider: npm
  skip_cleanup: true
  email: buildbot@beer-garden.io
  api_key:
    secure: PUnr41TsXE56o2LkExC8SWt5CVh1z2IBLr8zpFo+/LTbi+iBCnANdVQ+3/oO7znkBjdQjfTtaF2bTCn2Cnjg1LnW1dA4/IO7pBjUw+A5DjJqJ3Gr77qpDKYinuYxQGIOULoVW23PX8mqNbYOylWvQHc0Ua3T/v+w3lZfd+0uCBcjOmG0ksZ0Qmb8ErWHyMdpESTdn87e9H5w/Us7iGUoibqfyEIgfKUCLuIp9zSx9Y4rVFt2ZJh9LLW1pEPbSNxY8mkfYzgnUHTBZSBEziEG0oMlWGR99/2u4FBzLRZ1lBL8PraSkoI+zDmIEChKehP257teGXL+SI29pemQqO2aZaPvQVlkvkxOxcO/S/+e7XU1RXsohVoapwAalLe43r6YvgccB3T4sENyDd7bVcJ7+8MyeBkVCkaX8+ihMJIr1W8tmQVRNcbWc/ICYxz955ZjmU+a3QngcPvv8n31WgicSckLTmyxwzxmJ/59zZb9fYFzJ3cIrR7cBeXjOWZTmh+8S9DWu+e0MAlUJt1aaKx9BoJg3ULa5sS7WerAnmCl/S7xHbZgtIhtXXxJCI5/AapiWqFt3K8VMm6wi8wSBAcPeWmBs9ZI+nSDYkR7AtX1i7WIlttjO6nT4ED7iySRIkQdcWmdfULxoI9Y3qSs8Tnxa2hvYV+hCvzbs+Pn2c5z6Po=
  on:
    tags: true
    repo: beer-garden/angular-schema-form-builder

  # TODO - remove when not beta anymore
  tag: beta
