os: linux
dist: xenial
language: node_js

node_js:
- lts/*

script:
- echo "Fix the tests at some point please!"

before_deploy: npm run build
deploy:
  provider: npm
  skip_cleanup: true
  on:
    tags: true
    repo: beer-garden/angular-schema-form-builder
  email: beerbuildbot
  api_token:
    secure: n6eoWYgwvEzBzHD/iDm24ruK2fkeMijtSHyuclhzQiRwNQ46yf+U+pB0z/IfeY2N0ikmr/JfwXe4WvoMrzGrl3B7gr1nmnXeawkE7ypYu1m1xIwQDiW1yafgaxxdiv3m7UEjxIRsZ/bevpjYj3yBj6YAuOCtWiom7yXwaPmBSNv5p1nENtHOpzUTtc2qYm17zP6346ovo5vP38qUBJp2v1gwIxquBa3AAcgWk1bOGTPhL2fkv4WeY8QOsRiLiRY+v/8xnlVtnX1GzOIqvznNX23+yXxJqcmhfFkU0AuMGg5QOb8C/kEGbGr1n/gJHpvqF8HapE/rQ2nKHZrz3OevgJEQOvKbsMGpIc7zW1SZpYeGjByJcMAw6eR6N4dOdXGqwJNeNGeqfkMnxSTFG+rgqmA6AUnwn4J9J2D/qvUz7FQRgrSYF9Ih30UVFudlPdBOiKxr1WnQknO5toSaamiiJV2mdBdFzKMWbby8eMrenwbKIiL25znsYdMuKDLOEkFiCML2bVuVyesXt2s0yDloKZ2WjoWhNl8XWiVOP5hiuM/A9wM+R3Fk2EFqPhXNHULdbdAfH8A/8+q30RP/UlaFnVOnxz4nAyHgu+tP74k7qq3sXV202yrygCIFa+VfWPtxXPzIfniVaDeK1MPXwjZSOMDNTyKKb7BlrQC2NNKNjdk=

