language: node_js
node_js:
  - lts/*

script:
  - echo "Fix the tests at some point please!"

before_deploy: npm run build

deploy:
  provider: npm
  skip_cleanup: true
  email: buildbot@beer-garden.io
  api_key:
    secure: LeJxpWKP23piJ4DPAH5+nuUrRwFpbmRM0EY8nd63VOdDiLTSJGtrOaurMQ8NDivyYsvSS9GUxdqO7Ns+pX+/gZh3wQbOThELpe2hoMDSbl+tJcUPbEFBBqWpwl3hU/pU7A4RtoiVp63vRurgQxZQLLBFX5oL0bu9BzB2BAC8WBIy9oNtxT1SOM+HA3LDR+n78JJTcl1pOj9V2WH5jXGPSooRsZSRBCr5TIGt0CB5iZlAAr/pQPgHFMLIpY5Js/UIoOrVwwidFpbB9npEWnLaVeCr5+PTe970WnQIg6UKF2h7U2k5fRLK4Lt2zaUke+mH+aUhDgAUN5oDsdLNW/sBrwAqVwj1i6ZoQbpcl9YCHMGbOJWpzHSiEMmxIPAHDx6lj1KzGhDRcQCY9Yv/ZcgAadJ2BvdyM82Y9RKUvHoN7Gfxu+rcZdgtM0Ipq15hV5w/isAbY/WgvaOqiAyqj7ZBCcydXWBSOwsUNzXHW0nVMANM1XNzR7YxQbtueptPlz37/PVLF7W9CLDZvsHGW17QMyrWntZR+1PHuSTakkKdbN8QPnlQBtRFMnS3Gv+qiqYMvOnH63LEWZ/KwnQqF3sD2GIJPyJPXyf0886jyoKb5WwDouBaUWpzqCX9GDCcwT9qTMgXY1bagtDpE9cMl7SHqj92QUGCeeUOZYqMVzTBXo4=
  on:
    tags: true
    repo: beer-garden/angular-schema-form-builder
