name: Node.js Package

on:
  push:
    branches:
      - master

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
          
      - name: Authenticate with package registry
        run: |
          echo "//npm.pkg.github.com:_authToken=${{ secrets.NPM_TOKEN }}" >
          ~/.npmrc
          
      - run: npm run install
      - run: npm run build
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
